/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package progra2_eventos;

import javax.swing.JOptionPane;

/**
 *
 * @author Tommy Lee Pon
 */
public class Principal_FORM extends javax.swing.JFrame {

    private final Cuentas user;
    
    /**
     * Creates new form Principal_FORM
     */
    public Principal_FORM(Cuentas cuenta) {
        user=cuenta;
        initComponents();
        checkPrivilege(cuenta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombre_LABEL = new javax.swing.JLabel();
        crear_BUTTON = new javax.swing.JButton();
        eliminar_BUTTON = new javax.swing.JButton();
        editar_BUTTON = new javax.swing.JButton();
        ver_BUTTON = new javax.swing.JButton();
        back_BUTTON = new javax.swing.JButton();
        admin_BUTTON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Bienvenido, ");

        nombre_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombre_LABEL.setText("[NAME]");
        nombre_LABEL.setText(user.getNombre());

        crear_BUTTON.setText("Crear un evento");
        crear_BUTTON.setEnabled(false);
        crear_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_BUTTONActionPerformed(evt);
            }
        });

        eliminar_BUTTON.setText("Eliminar evento");
        eliminar_BUTTON.setEnabled(false);
        eliminar_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_BUTTONActionPerformed(evt);
            }
        });

        editar_BUTTON.setText("Editar Evento");
        editar_BUTTON.setEnabled(false);
        editar_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_BUTTONActionPerformed(evt);
            }
        });

        ver_BUTTON.setText("Ver evento");
        ver_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_BUTTONActionPerformed(evt);
            }
        });

        back_BUTTON.setText("Cerrar Sesión");
        back_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_BUTTONActionPerformed(evt);
            }
        });

        admin_BUTTON.setText("Administrar usuarios");
        admin_BUTTON.setEnabled(false);
        admin_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editar_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(admin_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crear_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminar_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ver_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back_BUTTON)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombre_LABEL)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombre_LABEL))
                .addGap(57, 57, 57)
                .addComponent(ver_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(crear_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminar_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editar_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(admin_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(back_BUTTON)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkPrivilege(Cuentas cuenta){
        if(cuenta.getTier()<2){
            crear_BUTTON.setEnabled(true);
            eliminar_BUTTON.setEnabled(true);
            editar_BUTTON.setEnabled(true);
        }
        if(cuenta.getTier()<1){
            admin_BUTTON.setEnabled(true);
        }
    }
    
    private void back_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_BUTTONActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login_FORM().setVisible(true);
    }//GEN-LAST:event_back_BUTTONActionPerformed

    private void admin_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_BUTTONActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Admin_FORM(user).setVisible(true);
    }//GEN-LAST:event_admin_BUTTONActionPerformed

    private void crear_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_BUTTONActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Crear_FORM(user).setVisible(true);
    }//GEN-LAST:event_crear_BUTTONActionPerformed

    private void eliminar_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_BUTTONActionPerformed
        // TODO add your handling code here:
        String codigo = JOptionPane.showInputDialog(this, "Insertar codigo de evento");
    }//GEN-LAST:event_eliminar_BUTTONActionPerformed

    private void editar_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_BUTTONActionPerformed
        // TODO add your handling code here:
        String codigo = JOptionPane.showInputDialog(this, "Insertat codigo de evento");
        if(user.srcCode(codigo)!=null){
            if(user.srcCode(codigo).getHost().equals(user.getUser())){
                new EditarEvento_FORM(user, user.srcCode(codigo)).setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "ERROR! Evento no pertenece al usuario");
            }
        } else {
            JOptionPane.showMessageDialog(null, "ERROR! Codigo no encontrado");
        }
    }//GEN-LAST:event_editar_BUTTONActionPerformed

    private void ver_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_BUTTONActionPerformed
        // TODO add your handling code here:
        String codigo = JOptionPane.showInputDialog(this, "Insertar codigo de evento");
    }//GEN-LAST:event_ver_BUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_FORM(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_BUTTON;
    private javax.swing.JButton back_BUTTON;
    private javax.swing.JButton crear_BUTTON;
    private javax.swing.JButton editar_BUTTON;
    private javax.swing.JButton eliminar_BUTTON;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombre_LABEL;
    private javax.swing.JButton ver_BUTTON;
    // End of variables declaration//GEN-END:variables
}
